// ©2023 Batty Bovine Productions, LLC. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"

#include "ComboInputTriggers.h"
#include "K2Node_Event.h"

#include "K2Node_ComboActionEvent.generated.h"


/**
 * Blueprint event node created for each UComboAction data asset, which is called
 * when the ComboManagerComponent activates the associated action.
 */
UCLASS()
class COMBOINPUTNODES_API UK2Node_ComboActionEvent : public UK2Node_Event
{
	GENERATED_BODY()

public:
	UK2Node_ComboActionEvent(const FObjectInitializer &ObjectInitializer);

	UPROPERTY()
		TObjectPtr<const class UComboAction> ComboAction;

	UPROPERTY()
		EComboActionTriggerEvent TriggerEvent;

	//~ Begin UK2Node Interface
	virtual UClass *GetDynamicBindingClass() const override;
	virtual void RegisterDynamicBinding(UDynamicBlueprintBinding *BindingObject) const override;
	//~ End UK2Node Interface
	
};
